services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: true
    volumes:
      - ./src:/src
      - ./logs:/logs
    env_file:
      - .env

networks:
  default:
    driver: bridge
